# Generated by Django 4.2.5 on 2023-10-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientuser',
            old_name='number',
            new_name='phone',
        ),
    ]
