# Generated by Django 4.2.5 on 2023-10-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_number_clientuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game', models.CharField(max_length=100)),
                ('Date_Time', models.DateTimeField()),
                ('Time_Needed', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='clientuser',
            name='mail',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
